#!/bin/sh 
PATH=/sbin:/bin:/usr/sbin:/usr/bin 
runlevel=S 
prevlevel=N 
umask 022 
export PATH runlevel prevlevel
echo "----------munt all----------------" 
mount -a
echo /sbin/mdev>/proc/sys/kernel/hotplug
mdev -s
echo "***********************************************" 
echo "****************Studying ARM Embedded *********************"
echo "Kernel version:linux-3.2.0" 
echo "Author QiuWeibo"
echo "Date:2014.08.07"
echo "***********************************************
#/bin/hostname -F /etc/sysconfig/HOSTNAME

